kind: Service
apiVersion: v1
metadata:
  name: gs-spring-boot-docker
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31416
  selector:
    app: gs-spring-boot-docker
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - ip: 172.171.49.219
